- name: Deploy via SSH
  uses: appleboy/ssh-action@v1
  with:
    host: ${{ secrets.VPS_HOST }}
    username: ${{ secrets.VPS_USER }}
    key: ${{ secrets.SSH_KEY }}
    script: |
      set -x

      cd ~/apps/miproyecto

      echo "Haciendo git pull..."
      git pull origin main

      echo "Activando entorno y variables..."
      source activate_env.sh

      echo "Instalando dependencias sin cache..."
      pip install --no-cache-dir -r requirements.txt

      echo "Reiniciando servicio uvicorn..."
      if sudo systemctl restart uvicorn.service; then
        echo "Servicio uvicorn reiniciado correctamente."
      else
        echo "Error al reiniciar uvicorn.service"
        echo "Mostrando último estado del servicio:"
        sudo systemctl status uvicorn.service --no-pager
        echo "Mostrando últimos logs del servicio:"
        sudo journalctl -u uvicorn.service -n 30 --no-pager
        exit 1
      fi

      echo "Deploy finalizado."
