name: Build and deploy Python app to Azure Web App - chatbotintercultural

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies only if not cached
        run: |
          python -m venv venv
          source venv/bin/activate
          if [ ! -d ~/.cache/pip ]; then
            echo "No pip cache found. Installing dependencies..."
            pip install --upgrade pip
            pip install -r requirements.txt
          else
            echo "Pip cache exists. Skipping install."
          fi


      - name: Prepare deployment package
        run: |
          zip -r deploy.zip . -x "venv/*" ".git/*" ".github/*" "__pycache__/*" "*.pyc"
          echo "Contents of deploy.zip:"
          unzip -l deploy.zip

      - name: Upload deployment package
        uses: actions/upload-artifact@v4
        with:
          name: deploy-package
          path: deploy.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download deployment package
        uses: actions/download-artifact@v4
        with:
          name: deploy-package

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_01E762BD95E24FBC85824C00F61A85BC }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A231BA571AD2427FA4CDDE54F69812A6 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_37342F2347D74A6EA94BF09E85C1E686 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'chatbotintercultural'
          slot-name: 'Production'
          package: deploy.zip

      - name: Show deployment logs (on failure)
        if: failure()
        run: |
          echo "Deployment failed. Consider checking Kudu logs at:"
          echo "https://<your-app-name>.scm.azurewebsites.net/api/logs/docker"
