name: Build and deploy Python app to Azure Web App - chatbotintercultural

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest commit only
        uses: actions/checkout@v4
        with:
          fetch-depth: 1  # Solo trae el último commit

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Prepare deployment package
        run: |
          zip -r deploy.zip . \
            -x "venv/*" ".venv/*" ".git/*" ".github/*" "__pycache__/*" "*.pyc" "*.pyo" "*.pyd" "*.db" \
            "*.zip" "*.tar" "*.gz" "*.log" "tests/*" "docs/*" "README.md" "LICENSE"

      - name: Show zip file size
        run: du -h deploy.zip

      - name: Upload deployment package
        uses: actions/upload-artifact@v4
        with:
          name: deploy-package
          path: deploy.zip 

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write       # Necesario para el login federado con Azure
      contents: read        # Necesario para acciones de checkout

    steps:
      - name: Download deployment package
        uses: actions/download-artifact@v4
        with:
          name: deploy-package

      - name: Ensure Azure secrets are set
        run: |
          if [ -z "${{ secrets.AZUREAPPSERVICE_CLIENTID_95F7D3D74047415399AC721FE77427E4 }}" ] || \
             [ -z "${{ secrets.AZUREAPPSERVICE_TENANTID_7E6F7A2F99D247549A09F0C7C10DB51A }}" ] || \
             [ -z "${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_81D4C71D70344E91825AB54AE8E18334 }}" ]; then
            echo "❌ Faltan secrets de Azure. Configúralos en Settings > Secrets and variables > Actions."
            exit 1
          fi

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_95F7D3D74047415399AC721FE77427E4 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7E6F7A2F99D247549A09F0C7C10DB51A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_81D4C71D70344E91825AB54AE8E18334 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'chatbotintercultural'
          slot-name: 'Production'
          package: deploy.zip
          verbose: true

      - name: Show deployment logs (on failure)
        if: failure()
        run: |
          echo "Deployment failed. Check logs:"
          echo "https://chatbotintercultural.scm.azurewebsites.net/api/logs/docker"
