name: Deploy Python App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd ~/apps/miproyecto

          # Actualizar código
          git pull origin main

          # Activar entorno y variables
          source activate_env.sh

          # Instalar dependencias
          pip install -r requirements.txt

          # Reiniciar app uvicorn
          # Primero mata cualquier uvicorn corriendo en el puerto 8000 (ajusta si usas otro)
          pkill -f "uvicorn servidor:app" || echo "No hay uvicorn corriendo"

          # Luego inicia uvicorn en background sin bloquear (ajusta ruta y puerto)
          nohup uvicorn servidor:app --host 0.0.0.0 --port 8000 &>/dev/null &
