name: Deploy Python App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          set -x

          cd ~/apps/miproyecto

          echo "Haciendo git pull..."
          git pull origin main

          echo "Activando entorno y cargando variables..."
          source activate_env.sh

          echo "Instalando dependencias sin cache..."
          pip install --no-cache-dir -r requirements.txt

          echo "Buscando procesos uvicorn para matar..."
          pids=$(pgrep -f "uvicorn servidor:app" | grep -v $$)
          if [ -z "$pids" ]; then
            echo "No hay procesos uvicorn para matar."
          else
            echo "Matando procesos uvicorn con PID: $pids"
            kill $pids
          fi

          echo "Iniciando uvicorn en background..."
          nohup uvicorn servidor:app --host 0.0.0.0 --port 8000 &

          echo "Deploy finalizado."
